name: cloc

on:
  pull_request:
  workflow_dispatch:

jobs:
  CLOC:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Count Lines of Code (cloc)
      uses: djdefi/cloc-action@3